CREATE SCHEMA IF NOT EXISTS DBACC;
DROP TABLE IF EXISTS DBACC.CUSTOMER_ACCOUNT;

CREATE TABLE DBACC.CUSTOMERS(
  CUSTOMER_ID VARCHAR(16)  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  SURNAME VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS DBACC.ACCOUNT;
CREATE TABLE DBACC.CUSTOMERS_ACCOUNT(ID INT AUTO_INCREMENT  PRIMARY KEY,
                           CUSTOMER_ID varchar(16),
                           CREDIT DECIMAL(20, 2),
                           TIMESTAMP TIME,
                           FOREIGN KEY (CUSTOMER_ID) references DBACC.CUSTOMERS(CUSTOMER_ID)
                           );